"""Markdown exporter — produces a plain Markdown file with YAML front matter."""
import re
from datetime import datetime, timezone


def _strip_html(html_content: str) -> str:
    """Very basic HTML → plain text stripping for the table cells."""
    text = re.sub(r'<[^>]+>', ' ', html_content)
    text = re.sub(r'&nbsp;', ' ', text)
    text = re.sub(r'&lt;', '<', text)
    text = re.sub(r'&gt;', '>', text)
    text = re.sub(r'\s+', ' ', text)
    return text.strip()


def export_markdown(report_type: str, title: str, session_id: str,
                    session_start, session_end, summary: dict,
                    ai_narrative: str | None, flows: list,
                    alerts: list) -> str:
    """
    Generate a Markdown representation of the report.
    Returns the Markdown string (caller writes it to disk).
    """
    now = datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')
    start_str = str(session_start)[:19] if session_start else 'N/A'
    end_str = str(session_end)[:19] if session_end else 'N/A'

    lines = [
        "---",
        f"report_type: {report_type}",
        f"title: \"{title}\"",
        f"session_id: {session_id}",
        f"period_start: {start_str}",
        f"period_end: {end_str}",
        f"generated: {now}",
        "---",
        "",
        f"# {title}",
        "",
        f"**Session:** `{session_id}`  ",
        f"**Period:** {start_str} — {end_str}  ",
        f"**Generated:** {now}",
        "",
    ]

    # Executive summary / AI narrative
    if ai_narrative:
        lines += ["## Executive Summary", "", ai_narrative, ""]

    # Stats
    if summary:
        lines += [
            "## Session Statistics",
            "",
            f"| Metric | Value |",
            f"|--------|-------|",
            f"| Total Flows | {summary.get('total_flows', 0):,} |",
            f"| Data Transferred | {_fmt_bytes(summary.get('total_bytes', 0))} |",
            f"| Avg RTT | {summary.get('avg_rtt_us', 0) / 1000:.1f} ms |",
            f"| Retransmits | {summary.get('total_retransmits', 0):,} |",
            f"| Unique Sources | {summary.get('unique_src_ips', 0):,} |",
            f"| Unique Destinations | {summary.get('unique_dst_ips', 0):,} |",
            "",
        ]

        proto_bd = summary.get("protocol_breakdown", [])
        if proto_bd:
            lines += ["### Protocol Breakdown", "", "| Protocol | Flows | Data |", "|----------|-------|------|"]
            for p in proto_bd:
                lines.append(f"| {p['protocol']} | {p['count']:,} | {_fmt_bytes(p['bytes'])} |")
            lines.append("")

    # Alerts
    if alerts:
        lines += [f"## Security Alerts ({len(alerts)} total)", "",
                  "| Severity | Title | Source IP |",
                  "|----------|-------|-----------|"]
        for a in alerts[:50]:
            lines.append(f"| {a.get('severity','?')} | {a.get('title','')} | {a.get('src_ip') or '—'} |")
        lines.append("")

    # Flow sample
    if flows:
        lines += [
            f"## Flow Sample (top {min(50, len(flows))})",
            "",
            "| Source | Destination | Protocol | Bytes | RTT | Retransmits |",
            "|--------|-------------|----------|-------|-----|-------------|",
        ]
        for f in flows[:50]:
            src = f"{f.get('src_ip')}:{f.get('src_port')}"
            dst = f"{f.get('dst_ip')}:{f.get('dst_port')}"
            proto = {6: 'TCP', 17: 'UDP', 1: 'ICMP'}.get(f.get('protocol', 0), '?')
            b = (f.get('fwd_bytes') or 0) + (f.get('rev_bytes') or 0)
            rtt = f"{f.get('avg_rtt_us', 0) / 1000:.1f}ms"
            retx = f.get('retransmit_count', 0) or 0
            lines.append(f"| `{src}` | `{dst}` | {proto} | {_fmt_bytes(b)} | {rtt} | {retx} |")
        lines.append("")

    lines.append("---")
    lines.append("*Generated by PeliCap Network Observability Platform*")

    return "\n".join(lines)


def _fmt_bytes(b: int | float) -> str:
    b = b or 0
    if b >= 1e9: return f"{b/1e9:.2f} GB"
    if b >= 1e6: return f"{b/1e6:.2f} MB"
    if b >= 1e3: return f"{b/1e3:.1f} KB"
    return f"{b:.0f} B"
